"""Add more fields to jobs table

Revision ID: 82491d3fdcd2
Revises: e4412e4199dc
Create Date: 2025-07-25 15:00:03.005158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82491d3fdcd2'
down_revision: Union[str, Sequence[str], None] = 'e4412e4199dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.alter_column('profiles', 'bio',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('profiles', 'skills',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'skills',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('profiles', 'bio',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               nullable=True)
    op.create_table('jobs',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('job_description', mysql.TEXT(), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('budget', mysql.FLOAT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('jobs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
